version: "3.9"

services:
  api:
    container_name: numberplatedetector
    image: numberplatedetector
    build: 
      context: ./src
    volumes:
      - './src:/src' #synchronizacja 
    ports:
      - 5000:5000